backend:
  name: github
  repo: Sebsatian2025/democms
  branch: main
  token: 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
  base_url: https://api.github.com

media_folder: "img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "site_content"
    label: "Contenido del sitio"
    files:

# HEADER
      - label: "Header"
        name: "header"
        file: "content/header.md"
        fields:
          - { label: "Tipo de fondo", name: "header_background_mode", widget: "select", options: ["image","color"], default: "image" }
          - { label: "Imagen de fondo", name: "header_background", widget: "image" }
          - { label: "Color de fondo de sección", name: "header_background_color", widget: "color", default: "#1d809f" }
          
          # NUEVOS CAMPOS DE COLOR 
          - { label: "Color del texto (Título/Subtítulo)", name: "header_text_color", widget: "color", default: "#ffffff" }
          - { label: "Color de fondo del botón", name: "header_button_bg_color", widget: "color", default: "#1d809f" }
          - { label: "Color del texto del botón", name: "header_button_text_color", widget: "color", default: "#ffffff" }
          # -----------------------------
          
          - { label: "Título principal (ES)", name: "header_title_es", widget: "string" }
          - { label: "Título principal (EN)", name: "header_title_en", widget: "string" }
          - { label: "Subtítulo (ES)", name: "header_subtitle_es", widget: "string" }
          - { label: "Subtítulo (EN)", name: "header_subtitle_en", widget: "string" }
          - { label: "Texto del botón (ES)", name: "header_button_text_es", widget: "string" }
          - { label: "Texto del botón (EN)", name: "header_button_text_en", widget: "string" }
          - { label: "Enlace del botón", name: "header_button_link", widget: "string" }

      # ABOUT
      - label: "About"
        name: "about"
        file: "content/about.md"
        fields:
          - { label: "Color de fondo", name: "about_background_color", widget: "color" }
          - { label: "Título (ES)", name: "about_title_es", widget: "string" }
          - { label: "Título (EN)", name: "about_title_en", widget: "string" }
          - { label: "Subtítulo (ES)", name: "about_subtitle_es", widget: "string" }
          - { label: "Subtítulo (EN)", name: "about_subtitle_en", widget: "string" }
          - { label: "Texto del botón (ES)", name: "about_button_text_es", widget: "string" }
          - { label: "Texto del botón (EN)", name: "about_button_text_en", widget: "string" }
          - { label: "Enlace del botón", name: "about_button_link", widget: "string" }

      # SERVICES
      - label: "Services"
        name: "services"
        file: "content/services.md"
        fields:
          - { label: "Color de fondo", name: "services_background_color", widget: "color" }
          - { label: "Color del subtítulo/Icono (ES)", name: "services_subtitle_color", widget: "color" }
          - { label: "Color del subtítulo/Icono (EN)", name: "services_subtitle_color_en", widget: "color" }
          - { label: "Subtítulo (ES)", name: "services_subtitle_es", widget: "string" }
          - { label: "Subtítulo (EN)", name: "services_subtitle_en", widget: "string" }
          - { label: "Título principal (ES)", name: "services_title_es", widget: "string" }
          - { label: "Título principal (EN)", name: "services_title_en", widget: "string" }
          - { label: "Clase de Icono 1", name: "service_icon_1_class", widget: "string", hint: "Ej: icon-screen-smartphone" } #  Clase del icono
          - { label: "Color de Icono 1", name: "service_icon_1_color", widget: "color" } #  Color del icono
          - { label: "Título servicio 1 (ES)", name: "service_title_1_es", widget: "string" }
          - { label: "Título servicio 1 (EN)", name: "service_title_1_en", widget: "string" }
          - { label: "Descripción servicio 1 (ES)", name: "service_desc_1_es", widget: "string" }
          - { label: "Descripción servicio 1 (EN)", name: "service_desc_1_en", widget: "string" }
          - { label: "Clase de Icono 2", name: "service_icon_2_class", widget: "string", hint: "Ej: icon-pencil" } #  NUEVO
          - { label: "Título servicio 2 (ES)", name: "service_title_2_es", widget: "string" }
          - { label: "Título servicio 2 (EN)", name: "service_title_2_en", widget: "string" }
          - { label: "Descripción servicio 2 (ES)", name: "service_desc_2_es", widget: "string" }
          - { label: "Descripción servicio 2 (EN)", name: "service_desc_2_en", widget: "string" }
          - { label: "Clase de Icono 3", name: "service_icon_3_class", widget: "string", hint: "Ej: icon-like" } #  NUEVO
          - { label: "Título servicio 3 (ES)", name: "service_title_3_es", widget: "string" }
          - { label: "Título servicio 3 (EN)", name: "service_title_3_en", widget: "string" }
          - { label: "Descripción servicio 3 (ES)", name: "service_desc_3_es", widget: "string" }
          - { label: "Descripción servicio 3 (EN)", name: "service_desc_3_en", widget: "string" }
          - { label: "Clase de Icono 4", name: "service_icon_4_class", widget: "string", hint: "Ej: icon-mustache" } #  NUEVO
          - { label: "Título servicio 4 (ES)", name: "service_title_4_es", widget: "string" }
          - { label: "Título servicio 4 (EN)", name: "service_title_4_en", widget: "string" }
          - { label: "Descripción servicio 4 (ES)", name: "service_desc_4_es", widget: "string" }
          - { label: "Descripción servicio 4 (EN)", name: "service_desc_4_en", widget: "string" }

      # CALLOUT
      - label: "Callout"
        name: "callout"
        file: "content/callout.md"
        fields:
          - { label: "Título (ES)", name: "callout_title_es", widget: "string" }
          - { label: "Título (EN)", name: "callout_title_en", widget: "string" }
          - { label: "Texto del botón (ES)", name: "callout_button_text_es", widget: "string" }
          - { label: "Texto del botón (EN)", name: "callout_button_text_en", widget: "string" }
          - { label: "Enlace del botón", name: "callout_button_link", widget: "string" }
          - { label: "Imagen de fondo", name: "callout_background", widget: "image" }

      # PORTFOLIO
      - label: "Portfolio"
        name: "portfolio"
        file: "content/portfolio.md"
        fields:
          - { label: "Imagen 1", name: "portfolio_img_1", widget: "image" }
          - { label: "Título imagen 1 (ES)", name: "portfolio_title_1_es", widget: "string" }
          - { label: "Título imagen 1 (EN)", name: "portfolio_title_1_en", widget: "string" }
          - { label: "Descripción imagen 1 (ES)", name: "portfolio_desc_1_es", widget: "string" }
          - { label: "Descripción imagen 1 (EN)", name: "portfolio_desc_1_en", widget: "string" }
          - { label: "Imagen 2", name: "portfolio_img_2", widget: "image" }
          - { label: "Título imagen 2 (ES)", name: "portfolio_title_2_es", widget: "string" }
          - { label: "Título imagen 2 (EN)", name: "portfolio_title_2_en", widget: "string" }
          - { label: "Descripción imagen 2 (ES)", name: "portfolio_desc_2_es", widget: "string" }
          - { label: "Descripción imagen 2 (EN)", name: "portfolio_desc_2_en", widget: "string" }
          - { label: "Imagen 3", name: "portfolio_img_3", widget: "image" }
          - { label: "Título imagen 3 (ES)", name: "portfolio_title_3_es", widget: "string" }
          - { label: "Título imagen 3 (EN)", name: "portfolio_title_3_en", widget: "string" }
          - { label: "Descripción imagen 3 (ES)", name: "portfolio_desc_3_es", widget: "string" }
          - { label: "Descripción imagen 3 (EN)", name: "portfolio_desc_3_en", widget: "string" }
          - { label: "Imagen 4", name: "portfolio_img_4", widget: "image" }
          - { label: "Título imagen 4 (ES)", name: "portfolio_title_4_es", widget: "string" }
          - { label: "Título imagen 4 (EN)", name: "portfolio_title_4_en", widget: "string" }
          - { label: "Descripción imagen 4 (ES)", name: "portfolio_desc_4_es", widget: "string" }
          - { label: "Descripción imagen 4 (EN)", name: "portfolio_desc_4_en", widget: "string" }

      # CTA
      - label: "Call to Action"
        name: "cta"
        file: "content/cta.md"
        fields:
          - { label: "Color de fondo", name: "cta_background_color", widget: "color" }
          - { label: "Título (ES)", name: "cta_title_es", widget: "string" }
          - { label: "Título (EN)", name: "cta_title_en", widget: "string" }
          - { label: "Texto botón 1 (ES)", name: "cta_button_1_text_es", widget: "string" }
          - { label: "Texto botón 1 (EN)", name: "cta_button_1_text_en", widget: "string" }
          - { label: "Enlace botón 1", name: "cta_button_1_link", widget: "string" }
          - { label: "Texto botón 2 (ES)", name: "cta_button_2_text_es", widget: "string" }
          - { label: "Texto botón 2 (EN)", name: "cta_button_2_text_en", widget: "string" }
          - { label: "Enlace botón 2", name: "cta_button_2_link", widget: "string" }

      # FOOTER
      - label: "Footer"
        name: "footer"
        file: "content/footer.md"
        fields:
          - { label: "Enlace Facebook", name: "footer_link_facebook", widget: "string" }
          - { label: "Enlace Twitter", name: "footer_link_twitter", widget: "string" }
          - { label: "Enlace GitHub", name: "footer_link_github", widget: "string" }
          - { label: "Texto copyright (ES)", name: "footer_copy_text_es", widget: "string" }
          - { label: "Texto copyright (EN)", name: "footer_copy_text_en", widget: "string" }
